# Generated by Django 5.2 on 2025-07-22 09:53

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_metier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du client"),
                ),
                (
                    "tenant_uuid",
                    models.UUIDField(help_text="UUID original du tenant", unique=True),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Tenant",
                "verbose_name_plural": "Clients Tenants",
            },
        ),
        migrations.RemoveField(
            model_name="adresse",
            name="tier",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="tier",
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenant_metier.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domaine",
                "verbose_name_plural": "Domaines",
            },
        ),
        migrations.DeleteModel(
            name="ActiviteTiers",
        ),
        migrations.DeleteModel(
            name="Adresse",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.DeleteModel(
            name="Tiers",
        ),
    ]
