# Generated by Django 5.0.1 on 2025-07-09 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tiers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "Nouvelle"),
                            ("needs_analysis", "Analyse des besoins"),
                            ("negotiation", "Négociation"),
                            ("won", "Gagnée"),
                            ("lost", "Perdue"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Étape",
                    ),
                ),
                (
                    "estimated_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant estimé"
                    ),
                ),
                (
                    "probability",
                    models.IntegerField(default=10, verbose_name="Probabilité (%)"),
                ),
                (
                    "expected_close_date",
                    models.DateField(verbose_name="Date de clôture prévue"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Site web"),
                            ("referral", "Recommandation"),
                            ("partner", "Partenaire"),
                            ("cold_call", "Démarchage"),
                            ("exhibition", "Salon/Exposition"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "assigned_to",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Assigné à (user_id)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Clôturé le"
                    ),
                ),
                (
                    "loss_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("price", "Prix"),
                            ("competitor", "Concurrent"),
                            ("timing", "Timing"),
                            ("no_budget", "Pas de budget"),
                            ("no_need", "Pas de besoin"),
                            ("no_decision", "Pas de décision"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Raison de perte",
                    ),
                ),
                (
                    "loss_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description de la perte"
                    ),
                ),
                (
                    "project_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID du projet",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="tiers.tiers",
                        verbose_name="Tiers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunité",
                "verbose_name_plural": "Opportunités",
                "db_table": "opportunites_opportunity",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["stage"], name="opportunite_stage_5c89a0_idx"),
                    models.Index(
                        fields=["source"], name="opportunite_source_207760_idx"
                    ),
                    models.Index(
                        fields=["tier"], name="opportunite_tier_id_902bd6_idx"
                    ),
                    models.Index(
                        fields=["assigned_to"], name="opportunite_assigne_151b24_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="opportunite_created_7ecd5e_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="opportunite_updated_ab9b40_idx"
                    ),
                    models.Index(
                        fields=["closed_at"], name="opportunite_closed__92495d_idx"
                    ),
                    models.Index(
                        fields=["probability"], name="opportunite_probabi_dcb9ff_idx"
                    ),
                    models.Index(
                        fields=["expected_close_date"],
                        name="opportunite_expecte_b3f8a3_idx",
                    ),
                    models.Index(
                        fields=["estimated_amount"],
                        name="opportunite_estimat_67c1ef_idx",
                    ),
                    models.Index(
                        fields=["loss_reason"], name="opportunite_loss_re_2cc8b0_idx"
                    ),
                    models.Index(
                        fields=["stage", "tier"], name="opportunite_stage_ffb4c4_idx"
                    ),
                    models.Index(
                        fields=["stage", "created_at"],
                        name="opportunite_stage_7ebf3d_idx",
                    ),
                    models.Index(
                        fields=["stage", "source"], name="opportunite_stage_8216ec_idx"
                    ),
                    models.Index(
                        fields=["stage", "assigned_to"],
                        name="opportunite_stage_dae89b_idx",
                    ),
                    models.Index(
                        fields=["stage", "probability"],
                        name="opportunite_stage_0afe63_idx",
                    ),
                    models.Index(
                        fields=["tier", "created_at"],
                        name="opportunite_tier_id_51906e_idx",
                    ),
                    models.Index(
                        fields=["tier", "stage"], name="opportunite_tier_id_228f05_idx"
                    ),
                    models.Index(
                        fields=["source", "created_at"],
                        name="opportunite_source_4ba8f9_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "created_at"],
                        name="opportunite_assigne_8e8a52_idx",
                    ),
                    models.Index(
                        fields=["stage", "tier", "created_at"],
                        name="opportunite_stage_9366e0_idx",
                    ),
                    models.Index(
                        fields=["stage", "source", "created_at"],
                        name="opportunite_stage_584699_idx",
                    ),
                    models.Index(
                        fields=["stage", "assigned_to", "created_at"],
                        name="opportunite_stage_3ca17a_idx",
                    ),
                ],
            },
        ),
    ]
