# Generated by Django 5.0.1 on 2025-07-18 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunites", "0001_initial"),
        ("tenant_metier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunities",
                to="tenant_metier.tiers",
                verbose_name="Tiers",
            ),
        ),
    ]
