# Generated by Django 5.2 on 2025-07-22 09:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tiers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("entreprise", "Entreprise"),
                            ("particulier", "Particulier"),
                        ],
                        db_index=True,
                        default="entreprise",
                        max_length=20,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="Nom"
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=14,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(regex="^\\d{14}$")
                        ],
                        verbose_name="SIRET",
                    ),
                ),
                (
                    "tva",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[A-Z]{2}\\d{9,13}$"
                            )
                        ],
                        verbose_name="Numéro TVA",
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("prospect", "Prospect"),
                            ("fournisseur", "Fournisseur"),
                            ("sous_traitant", "Sous-traitant"),
                        ],
                        db_index=True,
                        default="prospect",
                        help_text="Type de relation principale avec ce tier",
                        max_length=20,
                        verbose_name="Relation",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Archivé"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        verbose_name="Date de modification",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'archivage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tier",
                "verbose_name_plural": "Tiers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["type", "relation"], name="crm_tiers_type_9ec7d4_idx"
                    ),
                    models.Index(
                        fields=["relation", "created_at"],
                        name="crm_tiers_relatio_8f99df_idx",
                    ),
                    models.Index(
                        fields=["is_deleted", "relation"],
                        name="crm_tiers_is_dele_22910e_idx",
                    ),
                    models.Index(
                        fields=["type", "is_deleted"], name="crm_tiers_type_02524b_idx"
                    ),
                    models.Index(
                        fields=["nom", "siret"], name="crm_tiers_nom_3c0889_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=255, verbose_name="Nom"),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "Nouvelle"),
                            ("needs_analysis", "Analyse des besoins"),
                            ("negotiation", "Négociation"),
                            ("won", "Gagnée"),
                            ("lost", "Perdue"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="Étape",
                    ),
                ),
                (
                    "estimated_amount",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant estimé",
                    ),
                ),
                (
                    "probability",
                    models.IntegerField(
                        db_index=True,
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Probabilité (%)",
                    ),
                ),
                (
                    "expected_close_date",
                    models.DateField(
                        db_index=True, verbose_name="Date de clôture prévue"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Site web"),
                            ("referral", "Recommandation"),
                            ("partner", "Partenaire"),
                            ("cold_call", "Démarchage"),
                            ("exhibition", "Salon/Exposition"),
                            ("other", "Autre"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "assigned_to",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Assigné à (user_id)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Mis à jour le"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Clôturé le"
                    ),
                ),
                (
                    "loss_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("price", "Prix"),
                            ("competitor", "Concurrent"),
                            ("timing", "Timing"),
                            ("no_budget", "Pas de budget"),
                            ("no_need", "Pas de besoin"),
                            ("no_decision", "Pas de décision"),
                            ("other", "Autre"),
                        ],
                        db_index=True,
                        max_length=20,
                        null=True,
                        verbose_name="Raison de perte",
                    ),
                ),
                (
                    "loss_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description de la perte"
                    ),
                ),
                (
                    "project_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID du projet",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="crm.tiers",
                        verbose_name="Tiers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunité",
                "verbose_name_plural": "Opportunités",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["stage", "tier"], name="crm_opportu_stage_4bc95d_idx"
                    ),
                    models.Index(
                        fields=["stage", "created_at"],
                        name="crm_opportu_stage_469803_idx",
                    ),
                    models.Index(
                        fields=["stage", "source"], name="crm_opportu_stage_1528e4_idx"
                    ),
                    models.Index(
                        fields=["stage", "assigned_to"],
                        name="crm_opportu_stage_a9ce88_idx",
                    ),
                    models.Index(
                        fields=["stage", "probability"],
                        name="crm_opportu_stage_f73f86_idx",
                    ),
                    models.Index(
                        fields=["tier", "created_at"],
                        name="crm_opportu_tier_id_9d422a_idx",
                    ),
                    models.Index(
                        fields=["tier", "stage"], name="crm_opportu_tier_id_4d36b3_idx"
                    ),
                    models.Index(
                        fields=["source", "created_at"],
                        name="crm_opportu_source_b82348_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "created_at"],
                        name="crm_opportu_assigne_eb9487_idx",
                    ),
                    models.Index(
                        fields=["stage", "tier", "created_at"],
                        name="crm_opportu_stage_f8bf71_idx",
                    ),
                    models.Index(
                        fields=["stage", "source", "created_at"],
                        name="crm_opportu_stage_6d3999_idx",
                    ),
                    models.Index(
                        fields=["stage", "assigned_to", "created_at"],
                        name="crm_opportu_stage_9c40b5_idx",
                    ),
                    models.Index(
                        fields=["probability", "estimated_amount"],
                        name="crm_opportu_probabi_beabd4_idx",
                    ),
                    models.Index(
                        fields=["expected_close_date", "probability"],
                        name="crm_opportu_expecte_afbee9_idx",
                    ),
                    models.Index(
                        fields=["stage", "expected_close_date"],
                        name="crm_opportu_stage_ea8c40_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="Nom"
                    ),
                ),
                (
                    "prenom",
                    models.CharField(blank=True, max_length=100, verbose_name="Prénom"),
                ),
                (
                    "fonction",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fonction"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+?[0-9]{10,15}$"
                            )
                        ],
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "is_contact_principal_devis",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Contact principal devis",
                    ),
                ),
                (
                    "is_contact_principal_facture",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Contact principal facture",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="crm.tiers",
                        verbose_name="Tier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["nom", "prenom"],
                "indexes": [
                    models.Index(
                        fields=["tier", "is_contact_principal_devis"],
                        name="crm_contact_tier_id_543c84_idx",
                    ),
                    models.Index(
                        fields=["tier", "is_contact_principal_facture"],
                        name="crm_contact_tier_id_be2b9d_idx",
                    ),
                    models.Index(
                        fields=["nom", "prenom"], name="crm_contact_nom_96a4a8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Adresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Libellé"
                    ),
                ),
                (
                    "rue",
                    models.CharField(blank=True, max_length=255, verbose_name="Rue"),
                ),
                (
                    "ville",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="Ville"
                    ),
                ),
                (
                    "code_postal",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(regex="^\\d{5}$")
                        ],
                        verbose_name="Code postal",
                    ),
                ),
                (
                    "pays",
                    models.CharField(
                        default="France", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "is_facturation",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Adresse de facturation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adresses",
                        to="crm.tiers",
                        verbose_name="Tier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse",
                "verbose_name_plural": "Adresses",
                "ordering": ["-is_facturation", "libelle"],
                "indexes": [
                    models.Index(
                        fields=["tier", "is_facturation"],
                        name="crm_adresse_tier_id_7b763c_idx",
                    ),
                    models.Index(
                        fields=["ville", "code_postal"],
                        name="crm_adresse_ville_71c930_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActiviteTiers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("creation", "Création"),
                            ("modification", "Modification"),
                            ("appel", "Appel"),
                            ("email", "Email"),
                            ("rendez_vous", "Rendez-vous"),
                            ("devis", "Devis"),
                            ("facture", "Facture"),
                            ("autre", "Autre"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Type d'activité",
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(db_index=True, verbose_name="Utilisateur ID"),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date"
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activites",
                        to="crm.tiers",
                        verbose_name="Tier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité Tier",
                "verbose_name_plural": "Activités Tiers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tier", "type"], name="crm_activit_tier_id_1250aa_idx"
                    ),
                    models.Index(
                        fields=["tier", "created_at"],
                        name="crm_activit_tier_id_5743d3_idx",
                    ),
                    models.Index(
                        fields=["type", "created_at"],
                        name="crm_activit_type_01da94_idx",
                    ),
                    models.Index(
                        fields=["user_id", "created_at"],
                        name="crm_activit_user_id_6a5dfc_idx",
                    ),
                ],
            },
        ),
    ]
