# Generated by Django 5.0.1 on 2025-07-07 22:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tiers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("entreprise", "Entreprise"),
                            ("particulier", "Particulier"),
                        ],
                        default="entreprise",
                        max_length=20,
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=255, unique=True, verbose_name="Nom"),
                ),
                (
                    "siret",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="SIRET"
                    ),
                ),
                (
                    "tva",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Numéro TVA"
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("prospect", "Prospect"),
                            ("fournisseur", "Fournisseur"),
                            ("sous_traitant", "Sous-traitant"),
                        ],
                        default="prospect",
                        help_text="Type de relation principale avec ce tier",
                        max_length=20,
                        verbose_name="Relation",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Archivé"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "date_archivage",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'archivage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tier",
                "verbose_name_plural": "Tiers",
                "db_table": "tiers_tiers",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(fields=["type"], name="tiers_tiers_type_6c921c_idx"),
                    models.Index(
                        fields=["relation"], name="tiers_tiers_relatio_9ae797_idx"
                    ),
                    models.Index(
                        fields=["is_deleted"], name="tiers_tiers_is_dele_2167b6_idx"
                    ),
                    models.Index(
                        fields=["date_creation"], name="tiers_tiers_date_cr_ca59f9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(blank=True, max_length=100, verbose_name="Nom"),
                ),
                (
                    "prenom",
                    models.CharField(blank=True, max_length=100, verbose_name="Prénom"),
                ),
                (
                    "fonction",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fonction"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "contact_principal_devis",
                    models.BooleanField(
                        default=False, verbose_name="Contact principal devis"
                    ),
                ),
                (
                    "contact_principal_facture",
                    models.BooleanField(
                        default=False, verbose_name="Contact principal facture"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="tiers.tiers",
                        verbose_name="Tier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "db_table": "tiers_contact",
                "ordering": ["nom", "prenom"],
                "indexes": [
                    models.Index(
                        fields=["tier"], name="tiers_conta_tier_id_40acf4_idx"
                    ),
                    models.Index(fields=["email"], name="tiers_conta_email_6c295b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Adresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Libellé"
                    ),
                ),
                (
                    "rue",
                    models.CharField(blank=True, max_length=255, verbose_name="Rue"),
                ),
                (
                    "ville",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "code_postal",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code postal"
                    ),
                ),
                (
                    "pays",
                    models.CharField(
                        default="France", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "facturation",
                    models.BooleanField(
                        default=False, verbose_name="Adresse de facturation"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adresses",
                        to="tiers.tiers",
                        verbose_name="Tier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse",
                "verbose_name_plural": "Adresses",
                "db_table": "tiers_adresse",
                "ordering": ["-facturation", "libelle"],
                "indexes": [
                    models.Index(
                        fields=["tier"], name="tiers_adres_tier_id_51144f_idx"
                    ),
                    models.Index(
                        fields=["facturation"], name="tiers_adres_factura_e6a1ac_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActiviteTiers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("creation", "Création"),
                            ("modification", "Modification"),
                            ("appel", "Appel"),
                            ("email", "Email"),
                            ("rendez_vous", "Rendez-vous"),
                            ("devis", "Devis"),
                            ("facture", "Facture"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type d'activité",
                    ),
                ),
                ("utilisateur_id", models.UUIDField(verbose_name="Utilisateur ID")),
                ("contenu", models.TextField(verbose_name="Contenu")),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Date")),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activites",
                        to="tiers.tiers",
                        verbose_name="Tier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité Tier",
                "verbose_name_plural": "Activités Tiers",
                "db_table": "tiers_activitetiers",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["tier"], name="tiers_activ_tier_id_c65810_idx"
                    ),
                    models.Index(fields=["type"], name="tiers_activ_type_201efb_idx"),
                    models.Index(fields=["date"], name="tiers_activ_date_ddbfaf_idx"),
                    models.Index(
                        fields=["utilisateur_id"], name="tiers_activ_utilisa_82bedf_idx"
                    ),
                ],
            },
        ),
    ]
